version: "3"
services:

  wordpress:
    image: wordpress
    depends_on:
      - mysql:mysql
    links:
      - mysql:mysql
    ports:
      - 8080:80
    networks:
      - frontend
    deploy:
      replicas: 10
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password@123
    networks:
      - frontend
    deploy:
      placement:
        constraints: [node.role == manager]

  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    networks:
      - frontend
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]


networks:
  frontend:
